
baseURL: "https://fauwzk.github.io"
languageCode: "fr-fr"
title: "Portfolio"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: AP
      name: AP et Projets
      title: AP et Projets
      url: /projets/
      weight: 1
    - identifier: Stages
      name: Stages
      title: Stages
      url: /stages/
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Axel Polentes"
  description: Text about my cool site
  #staticPath: "/static"  # The path to serve the static files from
  favicon: "/images/moi.jpg"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Axel Polentes" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: true
      disableAchievements: true
      disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Bonjour, je suis"
    title: "Axel"
    subtitle: "Etudiant en BTS SIO"
    content: "Je bidouille ce qui touche de près ou de loin l'informatique. Un passe temps qui prend plus de temps que prévu."
    image: /images/moi.jpg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Mon CV"
      url: "cv.pdf"
      download: false
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/fauwzk

  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "BTS Service Informatique au Organisations"
        school:
          name: "Lycée Édmé Bouchardon, Chaumont"
          url: "https://lyc-bouchardon.monbureaunumerique.fr/"
        date: "2022 - Maintenant"
      - title: "Baccalauréat Technologique (STI2D Option EE)"
        school:
          name: "Lycée Phlippe Lebon, Joinville"
          url: "https://lyc-lebon.monbureaunumerique.fr/"
        date: "2019 - 2022"
      - title: "Collège"
        school:
          name: "Collège Joseph Cressot, Joinville"
          url: "https://clg-cressot.monbureaunumerique.fr/"
        date: "2015 - 2019"

  # About
  about:
    enable: false
    title: "A propos de moi"
    image: "/images/moi.jpg"
    content: |-
      Actuellement en BTS SIO, je suis passionné depuis longtemps d'informatqiue. 
    skills:
      enable: False
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "React"
        - "Node"
        - "Express"


  #Contact
  contact:
    enable: true
    title: "Contactez moi : "
    content: 
    btnName: Mon mail
    btnLink: mailto:polentesaxel@gmail.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Lu"
    toc: "Table du contenu"
    copyright: "Tous droits réservés"
    pageNotFound: "Page non trouvée"
    emailText: "Check out this site"

  datesFormat:
    article: "2 Jan 2006"
    articleList: "2 Jan 2006"
    articleRecent: "2 Jan 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
